stages:
  - install
  - test

install_deps:
  stage: install
  image: node:latest
  script:
    - node --version
    - npm install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

run_tests:
  stage: test
  image: node:latest
  script:
    - npm test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
